on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE: gchr.io/${{ github.repository }}

    steps:
      - run: echo "FROM alpine" > Dockerfile

      - run: ls
      
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: token
          password: ${{ github.token }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE }}
